Add ProgressMeter.jl support
tpapp/MultistartOptimization.jl pull request #10
Opened 2020-08-06 22:48 UTC by atrophiedbrain

2020-08-10 07:02 UTC, tpapp commented
Thanks for the PR. I will review it but currently I am very busy. Feel free to ping me in a week if I don't get to it.

2020-09-13 13:12 UTC, atrophiedbrain commented
@tpapp any issues I should address?

2020-09-13 13:23 UTC, tpapp requested changes
LGTM, just requested some style changes.

2020-09-13 13:23 UTC, tpapp commented on test/runtests.jl
> +    pr = true
Please test for all combinations (eg two outer for loops for `pr = [true, false]` etc).

2020-09-13 13:23 UTC, tpapp commented on test/runtests.jl
> +        p = multistart_minimization(multistart_method, local_method, P; progress=pr, parallel_sobol_points=psp)
```suggestion
        p = multistart_minimization(multistart_method, local_method, P; progress = pr, parallel_sobol_points = psp)
```

2020-09-13 13:23 UTC, tpapp commented on test/runtests.jl
> +        psp = true
```suggestion
```

2020-09-13 13:23 UTC, tpapp commented on src/MultistartOptimization.jl
> +
```suggestion
```
(removed dangling space)

2020-09-13 13:23 UTC, tpapp commented on src/MultistartOptimization.jl
> +    end
DRY, write something like
```julia
f(x) = @spawn(LocationValue(x, objective(x)))
```
and reuse it below.

2020-09-13 13:23 UTC, tpapp commented on src/MultistartOptimization.jl
> +function sobol_starting_points(minimization_problem::MinimizationProblem, N::Integer; parallel_map=true)
```suggestion
function sobol_starting_points(minimization_problem::MinimizationProblem, N::Integer; parallel_map = true)
```

2020-09-13 13:23 UTC, tpapp commented on src/MultistartOptimization.jl
>  An effort is made to parallelize the code using `Threads` when available.
document the `parallel_map` keyword argument (start a `# Keyword arguments` part)

2020-09-13 13:23 UTC, tpapp commented
Thanks for the ping, I just reviewed and requested some minor changes.

2021-02-07 13:55 UTC, tpapp commented
@atrophiedbrain, this is a very nice PR, are you still interested in finishing it?

2021-02-07 14:01 UTC, atrophiedbrain commented
I am, but school has me very preoccupied at the moment so it may be a while...

2021-02-08 12:24 UTC, tpapp commented
Perhaps a more generic way would be using [Folds.jl](https://discourse.julialang.org/t/ann-folds-jl-threaded-distributed-and-gpu-based-high-level-data-parallel-interface-for-julia/54701), which would allow the user to choose between threads and other implementations.

2021-04-21 08:11 UTC, closed without merging